Add: Header Component 추가
wecode-bootcamp-korea/fullstack2-1st-dashincode-frontend pull request #13
Opened 2021-10-05 01:51 UTC by dabin219

# PR 체크리스트

### PR을 올렸다면 아래 사항은 반드시 지켜주세요.

- [ ] Linked Issues에서 적절한 이슈 하나를 걸어두었습니다.
- [ ] Labels에서 적절한 라벨을 부착하였습니다.
- [ ] Projects에서 적절한 프로젝트를 할당하였습니다.
- [ ] 본 PR을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.

### 아래 사항까지 모두 체크되어야만 리뷰 요청 라벨을 달 수 있고, code review를 받을 수 있습니다.

- [ ] 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] npm start로 구현한 화면 혹은 기능을 확인할 수 있습니다.
- [ ] self-refactoring으로 wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.

### Peer Review

- [ ] 팀원 최소 2명 이상으로부터 Peer Review를 받고, 반영하였습니다.

> 마크다운에서 체크를 하기 위해서는 [x] 이렇게 수정하시면 됩니다. [x ], [ x ] 가 아니라 정확하게 [x]여야 합니다. 혹은 마우스 클릭으로 체크해주세요.

# 구현 화면

(여기에 구현 화면 스크린샷을 첨부해주세요)

# 이슈 체크리스트

(여기에 이슈에서 계획한 상세 구현 사항들을 체크리스트로 만들어 구현할 때마다 체크해주세요.)

- [ ] (예시) 회원가입 페이지 레이아웃 구현
- [ ] (예시) 아이디, password validation 기능 구현
- [ ] (예시) 이용약관 체크박스 기능 구현

## 기타 질문 및 특이 사항

(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

- (예시) 이용약관 체크박스 기능 구현 로직이 너무 지저분하고 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다!

2021-10-05 02:31 UTC, soheon-lee requested changes

2021-10-05 02:31 UTC, soheon-lee commented on src/components/Header/Header.js
> +          <Link to="/">
다빈님 현재 open 되어 있는 PR에 담겨있는 컴포넌트들이 모두 함수형이군요 :)
1차 프로젝트는 클래스형 컴포넌트로 진행됩니다. 변경부탁드립니다 👍

2021-10-05 03:01 UTC, dabin219 commented on src/components/Header/Header.js
> +          <Link to="/">
css 리팩토링 한 번 진행한 뒤 변경하겠습니다!! 감사합니다 :)

2021-10-05 09:37 UTC, goplanit approved these changes

2021-10-05 09:37 UTC, goplanit commented on src/components/Header/Header.js
> +        <container className="headerTop">
container Tag가 실제로 존재하는지 궁금합니다... 없다면 className에서 네이밍 이름 정해주세요 ㅎㅎ

2021-10-05 09:37 UTC, goplanit commented on src/components/Header/Header.js
> +        <container className="headerBottom">
여기도 tag 네이밍 바꿔주세요 ㅎㅎ

2021-10-05 09:38 UTC, shin-jungho approved these changes

2021-10-05 09:38 UTC, shin-jungho commented on src/components/Header/Header.scss
> +  overflow-x: hidden;
body에 css 써도 가능한가요????

2021-10-06 07:10 UTC, soheon-lee approved these changes

2021-10-06 07:10 UTC, merged