Add: footer 컴포넌트 수정중
wecode-bootcamp-korea/fullstack2-1st-dashincode-frontend pull request #25
Opened 2021-10-05 13:55 UTC by dabin219

# PR 체크리스트

### PR을 올렸다면 아래 사항은 반드시 지켜주세요.

- [ ] Linked Issues에서 적절한 이슈 하나를 걸어두었습니다.
- [ ] Labels에서 적절한 라벨을 부착하였습니다.
- [ ] Projects에서 적절한 프로젝트를 할당하였습니다.
- [ ] 본 PR을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.

### 아래 사항까지 모두 체크되어야만 리뷰 요청 라벨을 달 수 있고, code review를 받을 수 있습니다.

- [ ] 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] npm start로 구현한 화면 혹은 기능을 확인할 수 있습니다.
- [ ] self-refactoring으로 wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.

### Peer Review

- [ ] 팀원 최소 2명 이상으로부터 Peer Review를 받고, 반영하였습니다.

> 마크다운에서 체크를 하기 위해서는 [x] 이렇게 수정하시면 됩니다. [x ], [ x ] 가 아니라 정확하게 [x]여야 합니다. 혹은 마우스 클릭으로 체크해주세요.

# 구현 화면

(여기에 구현 화면 스크린샷을 첨부해주세요)

# 이슈 체크리스트

(여기에 이슈에서 계획한 상세 구현 사항들을 체크리스트로 만들어 구현할 때마다 체크해주세요.)

- [ ] (예시) 회원가입 페이지 레이아웃 구현
- [ ] (예시) 아이디, password validation 기능 구현
- [ ] (예시) 이용약관 체크박스 기능 구현

## 기타 질문 및 특이 사항

(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

- (예시) 이용약관 체크박스 기능 구현 로직이 너무 지저분하고 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다!

2021-10-06 06:58 UTC, Jtree03 requested changes

2021-10-06 06:58 UTC, Jtree03 commented on src/components/Footer/Footer.js
>    }
브라켓 하단 부분은 한줄 띄어주시기 바랍니다.

2021-10-06 06:58 UTC, Jtree03 commented on src/components/Footer/Footer.js
>    };
브라켓 하단 공백 추가

2021-10-06 06:58 UTC, Jtree03 commented on src/components/Footer/Footer.js
>        now: now.getHours(),
setState 필요없음.

2021-10-06 12:37 UTC, goplanit approved these changes
다빈님 너무 고생하셨어요~~ 2차 리뷰라 그런지 수정할만한게 잘 보이지가 않네요 ㅎㅎ 고생하셨어요~

2021-10-06 12:37 UTC, goplanit commented on src/components/Footer/Footer.js
> +      alert('오후에만 팅팅탱탱 상담이 가능합니다( ⁎ ᵕᴗᵕ ⁎ )');
네이밍이 참 좋습니다~ 👍

2021-10-06 12:48 UTC, dabin219 commented on src/components/Footer/Footer.js
> +      alert('오후에만 팅팅탱탱 상담이 가능합니다( ⁎ ᵕᴗᵕ ⁎ )');
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ제 아이디어의 한계입니다,,, ㅎㅎ

2021-10-07 02:54 UTC, dabin219 commented on src/components/Footer/Footer.js
> +        <div className="footerWrap">
지금 relative로 되어있는데 한단계 줄이고 이것저것 적용해보겠습니다 :)

2021-10-07 03:05 UTC, dabin219 commented on src/components/Footer/Footer.js
> +                })}
빼봤는데,, 맵을 돌려면 바깥에 묶어주는 태그가 필요하더라구요 ㅠㅠ hoxy.. 코드로 보여주실수있나요!!

2021-10-07 03:07 UTC, dabin219 commented on src/components/Footer/Footer.js
> +                  </a>
톡톡 상담은 외부 링크로 연결되어 새 창에서 네이버 톡톡이 뜹니다!!

2021-10-07 03:08 UTC, dabin219 commented on src/components/Footer/Footer.js
> +                  </a>
해봤지만 import 가 사용이 되지 않았다고 오류가 나서 아이콘이 정상적으로 뜨지 않습니다 ㅠㅠ

2021-10-07 05:06 UTC, jambottle approved these changes
다빈님, 요청하신 추가 리뷰 남겨뒀습니다!!

2021-10-07 05:06 UTC, jambottle commented on src/components/Footer/Footer.js
> +                })}
다빈님이 말씀하신 것처럼 바깥에서 묶어주는 태그로 `<ul> 태그`를 활용하고, `display: none;` 스타일로 마지막 `<li className="divider">|</li>` 요소(:last-child)만 없애주면 될 거라고 생각했는데요...

막상 코드 복사해서 구현해보니까 map 함수로 반복시키는 요소에 last-child나 nth-child로 접근하는 게 생각처럼 되질 않네요. 다빈님이 구현하신 코드로도 충분할 것 같다는 생각으로 다시 기우는데, 아래에 제가 생각한 코드를 공유하니 참고만 해주세요 😅

```
{footerTop.map((data, id) => {
  return (
    <ul key={id}>
      <Link to={data.link}>
        <li>{data.name}</li>
      </Link>
      <li>|</li>
    </ul>
  );
})}
```

2021-10-07 06:12 UTC, merged